name: Local Agent
version: 1.0.0
schema: v1
models:
  - name: qwen3-coder 30b
    provider: lmstudio
    model: qwen3/qwen3-coder-30b
    apiBase: http://localhost:1234/v1
  - name: gpt-oss-120b
    provider: lmstudio
    model: openai/gpt-oss-120b
    apiBase: http://localhost:1234/v1